from __future__ import annotations

import json


def build_tab_script(
    *,
    initial_tab: str,
    uses_broker_credentials: bool,
    kis_env_options_html: str,
    kis_template_real_fields: str,
    kis_template_paper_fields: str,
) -> str:
    return (
        "<script>(function(){"
        "const btns=Array.from(document.querySelectorAll('[data-settings-tab]'));"
        "const panels=Array.from(document.querySelectorAll('[data-settings-panel]'));"
        "panels.forEach(function(p){p.classList.remove('hidden');});"
        "if(!panels.length){return;}"
        "function activate(tab){"
        "var visible={'agents':['credentials','agents'],'capital':['capital'],'mcp':['mcp'],'memory':['memory'],'credentials':['credentials','agents']};"
        "var show=visible[tab]||[tab];"
        "btns.forEach(function(btn){"
        "var on=btn.getAttribute('data-settings-tab')===tab;"
        "btn.classList.toggle('bg-ink-900',on);"
        "btn.classList.toggle('text-white',on);"
        "btn.classList.toggle('border-ink-900',on);"
        "btn.classList.toggle('bg-white',!on);"
        "btn.classList.toggle('text-ink-700',!on);"
        "btn.classList.toggle('border-ink-200',!on);"
        "btn.classList.toggle('hover:bg-ink-50',!on);"
        "});"
        "panels.forEach(function(panel){"
        "var key=panel.getAttribute('data-settings-panel');"
        "panel.classList.toggle('hidden',show.indexOf(key)===-1);"
        "});"
        "document.dispatchEvent(new CustomEvent('settings-tab-activated',{detail:{tab:tab}}));"
        "}"
        "btns.forEach(function(btn){btn.addEventListener('click',function(){activate(btn.getAttribute('data-settings-tab'));});});"
        f"activate({json.dumps(initial_tab)});"
        "const mcpForm=document.getElementById('mcp-servers-form');"
        "if(mcpForm){"
        "const rowsHost=mcpForm.querySelector('[data-mcp-rows]');"
        "const hidden=mcpForm.querySelector('#mcp_servers_json_field');"
        "const addBtn=mcpForm.querySelector('[data-mcp-add]');"
        "function rowTemplate(){"
        "return '<div data-mcp-row class=\"grid gap-2 rounded-xl border border-ink-200/70 bg-white/70 p-3 md:grid-cols-[1fr_1.5fr_150px_110px_auto]\"><input data-field=\"name\" class=\"rounded-lg border border-ink-200 bg-white px-2 py-2 text-sm\" placeholder=\"name\"/><input data-field=\"url\" class=\"rounded-lg border border-ink-200 bg-white px-2 py-2 text-sm\" placeholder=\"https://...\"/><select data-field=\"transport\" class=\"rounded-lg border border-ink-200 bg-white px-2 py-2 text-sm\"><option value=\"sse\">sse</option><option value=\"streamable_http\">streamable_http</option></select><label class=\"inline-flex items-center gap-2 rounded-lg border border-ink-200 bg-white px-2 py-2 text-xs text-ink-700\"><input data-field=\"enabled\" type=\"checkbox\" checked class=\"h-4 w-4 rounded border-ink-300 text-ink-900\"/>enabled</label><button type=\"button\" data-mcp-remove class=\"rounded-lg border border-red-200 bg-red-50 px-2 py-2 text-xs font-semibold text-red-700 hover:bg-red-100\">Remove</button></div>';"
        "}"
        "function normalize(){"
        "const rows=Array.from(rowsHost.querySelectorAll('[data-mcp-row]'));"
        "const out=[];"
        "rows.forEach(function(row){"
        "const name=(row.querySelector('[data-field=\"name\"]')?.value||'').trim();"
        "const url=(row.querySelector('[data-field=\"url\"]')?.value||'').trim();"
        "const transport=(row.querySelector('[data-field=\"transport\"]')?.value||'sse').trim()||'sse';"
        "const enabled=!!row.querySelector('[data-field=\"enabled\"]')?.checked;"
        "if(!name && !url){return;}"
        "out.push({name:name,url:url,transport:transport,enabled:enabled});"
        "});"
        "hidden.value=JSON.stringify(out);"
        "}"
        "if(!rowsHost.querySelector('[data-mcp-row]')){rowsHost.insertAdjacentHTML('beforeend',rowTemplate());}"
        "rowsHost.addEventListener('click',function(ev){"
        "const btn=ev.target.closest('[data-mcp-remove]');"
        "if(!btn){return;}"
        "const row=btn.closest('[data-mcp-row]');"
        "if(row){row.remove();}"
        "if(!rowsHost.querySelector('[data-mcp-row]')){rowsHost.insertAdjacentHTML('beforeend',rowTemplate());}"
        "normalize();"
        "});"
        "rowsHost.addEventListener('change',normalize);"
        "rowsHost.addEventListener('input',normalize);"
        "if(addBtn){addBtn.addEventListener('click',function(){rowsHost.insertAdjacentHTML('beforeend',rowTemplate());normalize();});}"
        "mcpForm.addEventListener('submit',normalize);"
        "normalize();"
        "}"
        "var kisForm=document.getElementById('kis-accounts-form');"
        "if(kisForm){"
        "var kisRows=kisForm.querySelector('[data-kis-rows]');"
        "var kisHidden=kisForm.querySelector('#kis_accounts_json');"
        "var kisAdd=kisForm.querySelector('[data-kis-add]');"
        f"var kisUsesBrokerCredentials={json.dumps(uses_broker_credentials)};"
        f"var kisEnvOptions={json.dumps(kis_env_options_html)};"
        f"var kisRealFields={json.dumps(kis_template_real_fields)};"
        f"var kisPaperFields={json.dumps(kis_template_paper_fields)};"
        "function kisTemplate(){"
        "return '<div data-kis-row class=\"rounded-xl border border-ink-200/70 bg-white/70 p-4 space-y-2\"><div class=\"grid gap-2 sm:grid-cols-2\"><label class=\"text-sm text-ink-700\">ENV<select data-field=\"env\" class=\"mt-1 w-full rounded-xl border border-ink-200 bg-white px-3 py-2\">'+kisEnvOptions+'</select></label><label class=\"text-sm text-ink-700\">ACCOUNT NO<input data-field=\"account_no\" class=\"mt-1 w-full rounded-xl border border-ink-200 bg-white px-3 py-2\" placeholder=\"12345678-01\"/></label></div>'+kisRealFields+kisPaperFields+'<div class=\"flex justify-end\"><button type=\"button\" data-kis-remove class=\"rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-100\">Remove</button></div></div>';"
        "}"
        "function kisNormalize(){"
        "if(!kisUsesBrokerCredentials){kisHidden.value='[]';return;}"
        "var rows=Array.from(kisRows.querySelectorAll('[data-kis-row]'));"
        "var out=[];"
        "rows.forEach(function(row){"
        "var env=(row.querySelector('[data-field=\"env\"]')?.value||'real').trim()||'real';"
        "var account_no=(row.querySelector('[data-field=\"account_no\"]')?.value||'').trim();"
        "var app_key=(row.querySelector('[data-field=\"app_key\"]')?.value||'').trim();"
        "var app_secret=(row.querySelector('[data-field=\"app_secret\"]')?.value||'').trim();"
        "var paper_app_key=(row.querySelector('[data-field=\"paper_app_key\"]')?.value||'').trim();"
        "var paper_app_secret=(row.querySelector('[data-field=\"paper_app_secret\"]')?.value||'').trim();"
        "if(!account_no){return;}"
        "out.push({env:env,account_no:account_no,app_key:app_key,app_secret:app_secret,paper_app_key:paper_app_key,paper_app_secret:paper_app_secret});"
        "});"
        "kisHidden.value=JSON.stringify(out);"
        "}"
        "kisRows.addEventListener('click',function(ev){"
        "var btn=ev.target.closest('[data-kis-remove]');"
        "if(!btn){return;}"
        "var row=btn.closest('[data-kis-row]');"
        "if(row && kisRows.querySelectorAll('[data-kis-row]').length>1){row.remove();}"
        "kisNormalize();"
        "});"
        "kisRows.addEventListener('change',kisNormalize);"
        "kisRows.addEventListener('input',kisNormalize);"
        "if(kisAdd){kisAdd.addEventListener('click',function(){if(!kisUsesBrokerCredentials){return;} kisRows.insertAdjacentHTML('beforeend',kisTemplate());kisNormalize();});}"
        "kisForm.addEventListener('submit',kisNormalize);"
        "kisNormalize();"
        "}"
        "document.addEventListener('click',function(e){"
        "if(e.target.closest('.click-tip .tip-body a'))return;"
        "if(e.target.closest('.click-tip .tip-body'))return;"
        "var tip=e.target.closest('.click-tip');"
        "if(tip){"
        "e.preventDefault();e.stopPropagation();"
        "var body=tip.querySelector('.tip-body');"
        "if(!body)return;"
        "var wasOpen=body.classList.contains('open');"
        "document.querySelectorAll('.click-tip .tip-body.open').forEach(function(el){el.classList.remove('open');});"
        "if(!wasOpen)body.classList.add('open');"
        "return;"
        "}"
        "document.querySelectorAll('.click-tip .tip-body.open').forEach(function(el){el.classList.remove('open');});"
        "});"
        "})();</script>"
    )


def build_save_progress_script() -> str:
    return (
        "<script>(function(){"
        "const forms=Array.from(document.querySelectorAll('form[method=\"post\"]'));"
        "if(!forms.length){return;}"
        "function ensureMask(){"
        "let mask=document.getElementById('settings-save-mask');"
        "if(mask){return mask;}"
        "mask=document.createElement('div');"
        "mask.id='settings-save-mask';"
        "mask.style.position='fixed';"
        "mask.style.inset='0';"
        "mask.style.display='none';"
        "mask.style.alignItems='center';"
        "mask.style.justifyContent='center';"
        "mask.style.background='rgba(15,23,42,0.32)';"
        "mask.style.backdropFilter='blur(2px)';"
        "mask.style.zIndex='9998';"
        "const card=document.createElement('div');"
        "card.style.display='inline-flex';"
        "card.style.alignItems='center';"
        "card.style.gap='10px';"
        "card.style.padding='12px 14px';"
        "card.style.border='1px solid rgba(148,163,184,0.35)';"
        "card.style.borderRadius='12px';"
        "card.style.background='rgba(255,255,255,0.96)';"
        "card.style.boxShadow='0 10px 24px rgba(15,23,42,0.22)';"
        "const spinner=document.createElement('span');"
        "spinner.style.width='16px';"
        "spinner.style.height='16px';"
        "spinner.style.border='2px solid #cbd5e1';"
        "spinner.style.borderTopColor='#0f172a';"
        "spinner.style.borderRadius='9999px';"
        "spinner.style.display='inline-block';"
        "spinner.style.animation='arenaSpin 0.8s linear infinite';"
        "const text=document.createElement('span');"
        "text.style.fontSize='13px';"
        "text.style.fontWeight='700';"
        "text.style.color='#0f172a';"
        "text.textContent='Saving settings...';"
        "card.appendChild(spinner);"
        "card.appendChild(text);"
        "mask.appendChild(card);"
        "if(!document.getElementById('arena-spin-style')){"
        "const st=document.createElement('style');"
        "st.id='arena-spin-style';"
        "st.textContent='@keyframes arenaSpin{to{transform:rotate(360deg);}}';"
        "document.head.appendChild(st);"
        "}"
        "document.body.appendChild(mask);"
        "return mask;"
        "}"
        "forms.forEach(function(form){"
        "form.addEventListener('submit',function(ev){"
        "if(form.dataset.submitting==='1'){ev.preventDefault();return;}"
        "form.dataset.submitting='1';"
        "document.body.style.cursor='wait';"
        "const mask=ensureMask();"
        "mask.style.display='flex';"
        "const submitters=Array.from(form.querySelectorAll('button[type=\"submit\"],input[type=\"submit\"]'));"
        "submitters.forEach(function(btn){"
        "btn.disabled=true;"
        "btn.classList.add('opacity-60','cursor-not-allowed');"
        "if(btn.tagName==='INPUT'){btn.value='Saving...';}else{btn.textContent='Saving...';}"
        "});"
        "});"
        "});"
        "})();</script>"
    )
